# Site settings
title: Acari
email: alex@acari.io
description: > # this means to ignore newlines until "baseurl:"
  I can build an maintain a blog using version control. 
  I can also use continuous integration to build and deploy my blog.
  All of this is containerized :))))))).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sandwich" # the base hostname & protocol for your site
twitter_username: cyclic-reference
github_username:  cyclic-reference

# Build settings
# Conversion
markdown: kramdown
highlighter: rouge

defaults:
  - scope:
     path: "assets/images"
    values:
      image: true
