# Serve Settings
host: 0.0.0.0
port: 4000


# Site settings
title: Acari
email: alexsimons9999@gmail.com
author: Alex Simons
icon: reach_purple.png
description: > # this means to ignore newlines until "baseurl:"
  This site is a happy little aggregation of knowledge found
  when scowering the internet to solve bugs and issues. With a dash of cool things I learned
  I hope I was able to help!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sandwich:4000" # the base hostname & protocol for your site
imageDir: "http://sandwich:4000/assets/images/"
twitter_username: CyclicReference
github_username:  cyclic-reference

# Build settings
# Conversion
markdown: kramdown
highlighter: rouge

defaults:
  - scope:
     path: "assets/images"
    values:
      image: true


paginate: 4
