# Serve Settings
host: 0.0.0.0
port: 4000


# Site settings
title: Acari Blog
email: alexsimons9999@gmail.com
author: Alex Simons
icon: reach_purple.png
description: > # this means to ignore newlines until "baseurl:"
  Programming is a lot like going out for a hike.
  It's fun, challenging at times, rewarding, and there is always something new to learn.
  However, you can get easily get lost woods, have to trek over torturous terrain and
  there is a high probability that you come back with a few bugs attached to you.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
imageDir: "http://localhost:4000/assets/images/"
github_username:  cyclic-reference

# Build settings
# Conversion
markdown: kramdown
highlighter: rouge

defaults:
  - scope:
     path: "assets/images"
    values:
      image: true


paginate: 4
