# Serve Settings
host: 0.0.0.0
port: 4000


# Site settings
title: Unthrottled
email: alexsimons9999@gmail.com
author: Alex Simons
icon: reach_purple.png
description: >
  Programming is a lot like going out for a hike.
  It's fun, challenging at times, rewarding, and there is always something new to learn.
  However, you can get easily get lost woods, have to trek over torturous terrain, and
  there is a high probability that you come back with a few b̴̘̱̠̪̬̉̍͋̌̅̍u̴̘͒́̃̾͝ḡ̵̺̣̈̈͐s̷̨͓̗̣̖͑̃͒́͛̈̌ attached to you.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.unthrottled.com"
imageDir: /assets/images/
github_username:  Unthrottled

# Build settings
# Conversion
markdown: kramdown
highlighter: rouge

defaults:
  - scope:
     path: "assets/images"
    values:
      image: true


paginate: 4
